name: Continuous Integration

on:
  push:
    branches:
      - "ready/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          github_token: ${{ secrets.PAT}}

      - name: Test
        run: mvn test -DskipTests=false -Dgroups=fast

      - name: Compile
        run: mvn install

      - name: Push to Master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.PAT}}
