name: Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: mvn test -DskipTests=false -Dgroups=slow
      - name: Push to Release
        run: |
          git checkout master
          git branch release
          git push -f origin master:release