name: Staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.PAT}}

      - name: Test
        run: mvn test -DskipTests=false -Dgroups=slow
      - name: Push to Release
        run: |
          git checkout master
          git rebase origin/release
          git branch release
          git push origin release:release
