name: Staging

on:
  workflow_run:
    workflows: [ "Continuous Integration" ]
    types:
      - completed
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: mvn test -DskipTests=false -Dgroups=slow
      - name: Push to Release
        run: |
          git checkout master
          git rebase origin/release
          git branch release
          git push origin release:release
          git push origin :${GITHUB_REF#refs/heads/}
